pre-commit = "python tasks.py formatcheck"
pre-push = "pytest"

# [forbidden-strings]
# Checked in staged files during pre-commit.
# Key = literal string, Value = glob pattern(s) ("*" for all files)
# "<<<<<<< " = "*"
# "console.log" = ["*.py", "*.ts"]
# "binding.pry" = "*.rb"
